export const CHARACTER_BANKS = {
  global: {
    // Easter egg roster sourced from Chapman's official Fowler School of Engineering faculty directory.
    facultyNames: [
      "Doaa AbouZeid",
      "Rao Ali",
      "Mohamed Allali",
      "Daniel Alpay",
      "Emad Arasteh",
      "Ryan Bakonis",
      "Vincent Berardi",
      "Chris Bolduc",
      "LouAnne Boyd",
      "Franceli Cibrian",
      "Jacob Cohn",
      "Kendra Day",
      "Thomas DuPont",
      "Elia Eiroa Lledo",
      "Maryam Etezadbrojerdi",
      "Michael Fahy",
      "Christopher Girard",
      "Kendall Harris",
      "Mark Harrison",
      "Doug Havard",
      "Kristina Horn",
      "Jonathan Humphreys",
      "Joby John",
      "Rajeev Joshi",
      "Alexander Kurz",
      "Nick LaHaye",
      "Samuel Lee",
      "Anthony Lemus",
      "Erik Linstead",
      "L. Andrew Lyon",
      "Brandon Makin",
      "Uri Maoz",
      "Alireza Mehrnia",
      "Nasim Mohammadi Estakhri",
      "Nooshin Mohammadi Estakhri",
      "David Molinero Giles",
      "Amy Moors",
      "Ismieal Muhsin",
      "Chelsea Parlett",
      "Farid Parvini",
      "Thomas Piechota",
      "Derek Prate",
      "Cassandra Maya",
      "Trudi Qi",
      "Natalia Sanchez Aldana",
      "Sarahzin Shane",
      "Rahul Soangra",
      "Timothy Springer",
      "Tom Springer",
      "Elizabeth Stevens",
      "Sergey Sundukovskiy",
      "Steve Tran",
      "Gabriela Shirkey",
      "Jacqueline Henriksen",
      "Nicole Wagner",
      "Jonathan Weinberger",
      "Miyuki Weldon",
      "Yuxin Wen",
      "Peiyi Zhao",
      "Amanda Frazier",
      "Javier Espeleta",
      "Sayani Ghosh",
      "Joelle Prate",
      "Daniel Cárdenas",
      "Ariane Jong-Levinger",
      "Sarah Arnette",
      "Aracely Acevedo"
    ],
    featuredFacultyNames: [
      "Kendall Harris",
      "LouAnne Boyd",
      "Anthony Lemus",
      "Erik Linstead",
      "Thomas Piechota",
      "Trudi Qi",
      "Nicole Wagner",
      "Jonathan Weinberger",
      "Jacqueline Henriksen",
      "Cassandra Maya",
      "Gabriela Shirkey",
      "Amanda Frazier",
      "Javier Espeleta",
      "Sayani Ghosh",
      "Joelle Prate",
      "Daniel Cárdenas",
      "Ariane Jong-Levinger",
      "Sarah Arnette",
      "Aracely Acevedo",
    ],
    traits: [
      { text: "Calm under cascading pressure", tags: ["steady", "leader"] },
      { text: "Absorbs chaos and returns clarity", tags: ["steady", "leader"] },
      { text: "Reads morale shifts before anyone speaks them aloud", tags: ["empathetic", "social"] },
      { text: "Turns panic into procedure", tags: ["procedural", "steady"] },
      { text: "Curiosity sharp enough to feel dangerous", tags: ["curious", "bold"] },
      { text: "Balances awe with disciplined observation", tags: ["curious", "measured"] },
      { text: "Most comfortable at the edge of the risk envelope", tags: ["risk", "bold"] },
      { text: "Keeps calm when the environment turns violent", tags: ["steady", "risk"] },
      { text: "Finds structure in noise before anyone else notices the pattern", tags: ["analytical", "curious"] },
      { text: "Most confident when the alarm stack is overflowing", tags: ["procedural", "bold"] },
      { text: "Treats uncertainty like something that can be organized", tags: ["procedural", "analytical"] },
      { text: "Radiates confidence when systems start to buckle", tags: ["leader", "bold"] },
      { text: "Has a quiet instinct for the worst-case scenario", tags: ["cautious", "analytical"] },
      { text: "Moves with deliberate calm when everyone else speeds up", tags: ["steady", "measured"] },
      { text: "Can make hard choices without letting them sound cruel", tags: ["leader", "empathetic"] },
      { text: "Notices mechanical patterns hidden inside chaos", tags: ["analytical", "procedural"] },
      { text: "Pushes through fear by focusing on the next practical step", tags: ["procedural", "risk"] },
      { text: "Feels most alive when the mission becomes difficult", tags: ["risk", "bold"] },
      { text: "Can hold contradictory truths without freezing", tags: ["measured", "analytical"] },
      { text: "Finds meaning in fragments before the picture is complete", tags: ["curious", "intuitive"] },
    ],
    flaws: [
      { text: "Carries too much alone before delegating", tags: ["control", "closed"] },
      { text: "Can mistake control for safety", tags: ["control", "cautious"] },
      { text: "Pushes forward before consensus fully forms", tags: ["impulsive", "control"] },
      { text: "Pushes damaged systems long past the safe window", tags: ["reckless", "procedural"] },
      { text: "Cuts safety margins too aggressively under time pressure", tags: ["reckless", "speed"] },
      { text: "Can chase understanding past the point of safety", tags: ["obsessive", "curious"] },
      { text: "Hides how personally invested they become in unexplained phenomena", tags: ["closed", "obsessive"] },
      { text: "Understates injuries if the mission still has momentum", tags: ["self_erasing", "reckless"] },
      { text: "Takes on the highest-risk task by reflex", tags: ["reckless", "risk"] },
      { text: "Treats pain like irrelevant background data", tags: ["self_erasing", "closed"] },
      { text: "Has trouble admitting when the situation is slipping", tags: ["control", "closed"] },
      { text: "Commits to a plan so hard that pivots come late", tags: ["rigid", "control"] },
      { text: "Can sound colder than intended when stress peaks", tags: ["abrasive", "closed"] },
      { text: "Rationalizes one more dangerous step when progress is visible", tags: ["reckless", "obsessive"] },
      { text: "Pushes themself past exhaustion before asking for relief", tags: ["self_erasing", "rigid"] },
      { text: "Trusts instinct faster than the room can keep up", tags: ["impulsive", "bold"] },
      { text: "Lets curiosity blur the line between observation and contact", tags: ["obsessive", "curious"] },
      { text: "Minimizes personal risk until it becomes everyone else's problem", tags: ["reckless", "closed"] },
      { text: "Overcorrects after mistakes and burns time doing it", tags: ["rigid", "cautious"] },
      { text: "Keeps secrets when vulnerability would probably help", tags: ["closed", "social"] },
    ],
  },
  commander: {
    callSigns: [
      "Aegis",
      "Bulwark",
      "Anchor",
      "Northstar",
      "Sentinel",
      "Helm",
      "Palisade",
      "Torchline",
      "Signalfire",
      "Steadfast",
      "Commandant",
      "Bluebook",
      "Keystone",
      "Overwatch",
      "Crownline",
      "Vector Prime",
      "Linehold",
      "Beacon Six",
      "Highrail",
      "Sternlight",
    ],
    specialties: [
      "Command tempo and crisis triage",
      "Battlefield delegation and emergency route planning",
      "Crew stabilization and mission reprioritization",
      "Operational tempo and high-risk command timing",
      "Cross-discipline decision control under signal loss",
      "Rapid mission reprioritization under cascading failure",
      "Crew cohesion during comms loss and isolation",
      "Risk balancing across simultaneous critical tasks",
      "Decision architecture under incomplete telemetry",
      "Surface-command timing during EVA instability",
    ],
    stakes: [
      "Will not lose another mission under their command",
      "Refuses to let another crew disappear under their watch",
      "Needs this mission to prove they can lead in deep-field isolation",
      "Believes hesitation is what killed a previous mission partner",
      "Needs to bring every crew member home to justify one brutal call years ago",
      "Knows one more failed command will end their flight career for good",
      "Needs this mission to prove their crew-first doctrine actually works",
      "Is trying to outrun the reputation of one catastrophic command review",
      "Believes this crew is their last real chance to get leadership right",
      "Cannot face another memorial built around a decision they made",
    ],
  },
  flight_engineer: {
    callSigns: [
      "Patchbay",
      "Sparkwell",
      "Fuse",
      "Weld",
      "Relay",
      "Bypass",
      "Latchkey",
      "Circuit",
      "Drydock",
      "Spanner",
      "Coldstart",
      "Busbar",
      "Ratchet",
      "Loadline",
      "Fixpoint",
      "Mainbreak",
      "Flux",
      "Hammerlock",
      "Shunt",
      "Relay Nine",
    ],
    specialties: [
      "Life support stabilization and field repair",
      "Power routing and improvised hardware salvage",
      "Life support repair and subsystem triage",
      "Pressure seal recovery and thermal control repair",
      "Redundant systems management under cascading faults",
      "Scrubber maintenance and emergency bypass design",
      "Thermal loop recovery under hardware stress",
      "Improvised field repair with depleted tool access",
      "Power isolation during multi-system failure",
      "Rover survivability management after structural damage",
    ],
    stakes: [
      "Knows the rover only gets one real failure before people start dying",
      "Built half this rover and refuses to watch it die in silence",
      "Needs to prove the maintenance doctrine they wrote actually works in the field",
      "Won't return home as the engineer who lost the air loop",
      "Needs this mission to validate years spent defending risky hardware upgrades",
      "Is determined not to be remembered as the engineer who missed the obvious fault",
      "Needs this deployment to vindicate a controversial patch architecture",
      "Believes the rover can survive if they do not blink first",
      "Still carries the guilt of one preventable systems loss from training command",
      "Needs one field success before the program sidelines them permanently",
    ],
  },
  science_officer: {
    callSigns: [
      "Spectra",
      "Prism",
      "Cipher",
      "Halo",
      "Lattice",
      "Echoform",
      "Array",
      "Ghostline",
      "Parallax",
      "Signalglass",
      "Tessellate",
      "Blue Shift",
      "Lumen",
      "Afterimage",
      "Quiet Arc",
      "Vector Glass",
      "Ion Bloom",
      "Null Echo",
      "Sundial",
      "Deepband",
    ],
    specialties: [
      "Signal analysis and anomaly interpretation",
      "Signal decoding and anomaly modeling",
      "Telemetry synthesis and buried-data reconstruction",
      "Lunar geology correlation and exotic pattern detection",
      "Pattern analysis across corrupted telemetry fields",
      "Deep-noise interpretation under severe interference",
      "Artifact discrimination across overlapping sensor returns",
      "Geometric burst analysis and carrier reconstruction",
      "Subsurface anomaly inference from partial scan data",
      "Temporal pattern recognition inside repeating telemetry events",
    ],
    stakes: [
      "Believes this signal could redefine humanity's place on the moon",
      "Needs this find to vindicate a theory the program mocked for years",
      "Believes this signal could redeem a career damaged by one bad call",
      "Needs proof that the moon still holds something no one else has seen",
      "Needs this anomaly to be real enough to justify a lifetime of obsession",
      "Cannot return empty-handed after staking their reputation on this search window",
      "Needs a discovery large enough to survive the politics waiting back on Earth",
      "Believes this is the first real evidence that the moon remembers more than humans do",
      "Needs the data to prove their last failed interpretation was not incompetence",
      "Has spent too many years chasing false signals to walk away from this one",
    ],
  },
  mission_specialist: {
    callSigns: [
      "Waypoint",
      "Latch",
      "Vector",
      "Spindle",
      "Torch",
      "Hardline",
      "Rook",
      "Grapple",
      "Stride",
      "Rimfire",
      "Hookline",
      "Kestrel",
      "Driftpin",
      "Hardstep",
      "Latchpoint",
      "Outrider",
      "Icehook",
      "Redline",
      "Tether",
      "Farwalk",
    ],
    specialties: [
      "EVA deployment and field improvisation",
      "Surface traversal and emergency field extraction",
      "Relay deployment and improvised surface rigging",
      "Airlock breach response and EVA improvisation",
      "Surface hazard response under comms degradation",
      "Hazard crossing during compromised suit conditions",
      "Field relay placement in unstable terrain",
      "Manual retrieval and rescue under blackout risk",
      "Rapid external repair during environmental exposure",
      "Anchor placement and mobility routing across fractured ground",
    ],
    stakes: [
      "Needs this mission to prove the last surface accident was not a career-ending failure",
      "Needs a clean mission after the EVA loss that still follows them",
      "Wants this operation to erase the label of liability from their record",
      "Needs this mission to prove they still belong outside the airlock",
      "Needs one flawless field op before command buries them behind a desk",
      "Refuses to let one old mistake become the last thing people remember about them",
      "Needs this deployment to prove they are more than a risk waiver with a pulse",
      "Believes one successful EVA can rewrite the narrative of their whole career",
      "Cannot go back to Earth with another mission aborted at the hatch",
      "Needs to prove they can still be trusted with the outside of the vehicle",
    ],
  },
};

export const SPECIAL_CREW_OVERRIDES = {
  "Jacqueline Henriksen": {
    callSigns: ["Ritz", "Orange Bird"],
  },
};

export const CREW_TENSION_PATTERNS = [
  {
    roles: ["Commander", "Mission Specialist"],
    summary: "Command discipline keeps colliding with field improvisation.",
    preferredTags: [
      ["control", "steady", "leader"],
      ["risk", "reckless", "bold"],
    ],
  },
  {
    roles: ["Flight Engineer", "Science Officer"],
    summary: "Engineering caution is grinding against anomaly obsession.",
    preferredTags: [
      ["procedural", "cautious", "rigid"],
      ["curious", "obsessive", "intuitive"],
    ],
  },
  {
    roles: ["Commander", "Science Officer"],
    summary: "Operational urgency is clashing with the need to understand the signal.",
    preferredTags: [
      ["leader", "control", "steady"],
      ["curious", "obsessive", "analytical"],
    ],
  },
  {
    roles: ["Flight Engineer", "Mission Specialist"],
    summary: "Safety margins are in constant argument with field momentum.",
    preferredTags: [
      ["cautious", "procedural", "rigid"],
      ["risk", "bold", "impulsive"],
    ],
  },
];
